#Deployment manifest to create the MariaDB pod
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mariadb-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
      - name: mariadb
        image: hngtech11/mariadb
        envFrom:
        - secretRef:
            name: mariadb.auth
        
        env:
        - name: MARIADB_USER
          valueFrom: 
            secretKeyRef:
              name: mariadb.auth
              key: MARIADB_USER

        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb.auth
              key:  MARIADB_PASSWORD

        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb.auth
              key: MARIADB_DATABASE
              
---

#Manifest for creating the MariaDB Service
apiVersion: v1

kind: Service

metadata:
  name: mariadb-service

spec:
  type: NodePort
  selector:
    app: mariadb

  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306