#Manifest for deploying the WordPress pod
apiVersion: apps/v1

kind: Deployment

metadata:
  name: wordpress-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress

  template:
    metadata:
      labels:
        app: wordpress

    spec:
      containers:
      - name: wordpress
        image: hngtech11/wordpress

        #declare the configMap and Secret. The db credentials are stored in the secret.
        envFrom:
        - configMapRef:
            name: wordpress-config
        - secretRef:
            name: mariadb.auth

        env:
        - name: WORDPRESS_DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DATABASE_HOST

        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb.auth
              key: MARIADB_USER

        - name: WORDPRESS_DATABASE_PASSWORD 
          valueFrom: 
            secretKeyRef:
              name: mariadb.auth
              key: MARIADB_PASSWORD

        - name: WORDPRESS_DATABASE_NAME
          valueFrom: 
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DATABASE_NAME

        ports:
          - containerPort: 8443
          - containerPort: 8080

---

#manifest to create the wordpress service
apiVersion: v1

kind: Service

metadata:
  name: wordpress-service

spec:
  type: NodePort
  selector:
    app: wordpress

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000